production:
  api_name: "Space API"
  repo_url: "https://github.com/rhannequin/space-api"
  api_url:  "https://space-api.herokuapp.com/api"
  proxy_use: false
  proxy_url:
  proxy_port:
  proxy_username:
  proxy_password:
development:
  api_name: 'Space API'
  repo_url: 'https://github.com/rhannequin/space-api'
  api_url: "http://localhost:5000/api"
  proxy_use: false
  proxy_url:
  proxy_port:
  proxy_username:
  proxy_password:
test:
  api_name: 'Space API'
  repo_url: 'https://github.com/rhannequin/space-api'
  api_url: "http://localhost:5000/api"
  proxy_use: false
  proxy_url:
  proxy_port:
  proxy_username:
  proxy_password:
