require_relative 'models/sun'
require_relative 'models/sun_now'

require_relative 'models/mercury'
require_relative 'models/mercury_now'
require_relative 'models/venus'
require_relative 'models/venus_now'
require_relative 'models/mars'
require_relative 'models/mars_now'
require_relative 'models/earth'
require_relative 'models/earth_now'
require_relative 'models/jupiter'
require_relative 'models/jupiter_now'
require_relative 'models/saturn'
require_relative 'models/saturn_now'
require_relative 'models/uranus'
require_relative 'models/uranus_now'
require_relative 'models/neptune'
require_relative 'models/neptune_now'
require_relative 'models/pluto'
require_relative 'models/pluto_now'

require_relative 'models/moon'
require_relative 'models/moon_now'

require_relative 'models/planet_tmp'
