require_relative 'models/sun'
require_relative 'models/sun_now'

require_relative 'models/mercury'
require_relative 'models/mercury_now'
# require_relative 'models/Venus'
# require_relative 'models/Earth'
# require_relative 'models/Mars'
# require_relative 'models/Jupiter'
# require_relative 'models/Saturn'
# require_relative 'models/Uranus'
# require_relative 'models/Neptune'
# require_relative 'models/Pluto'

require_relative 'models/moon'
require_relative 'models/moon_now'
